import { NextRequest, NextResponse } from "next/server";
import { supabaseAdmin } from "@/lib/supabase";

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { name, email, type, message } = body;

    // Basic validation
    if (!email || !message) {
      return NextResponse.json(
        { success: false, error: "이메일과 내용을 입력해주세요." },
        { status: 400 }
      );
    }

    if (!supabaseAdmin) {
      console.error("Supabase client not initialized");
      return NextResponse.json(
        { success: false, error: "서버 설정 오류입니다." },
        { status: 500 }
      );
    }

    // Insert into 'contact_messages' table
    // User needs to create this table:
    /*
      create table contact_messages (
        id bigint generated by default as identity primary key,
        created_at timestamp with time zone default timezone('utc'::text, now()) not null,
        name text,
        email text,
        type text,
        message text,
        status text default 'unread'
      );
    */
    const { error } = await supabaseAdmin.from("contact_messages").insert([
      {
        name,
        email,
        type,
        message,
        created_at: new Date().toISOString(),
      },
    ]);

    if (error) {
      console.error("Contact message insert error:", error);
      return NextResponse.json(
        { success: false, error: "문의 접수에 실패했습니다." },
        { status: 500 }
      );
    }

    return NextResponse.json({
      success: true,
      message: "문의가 성공적으로 접수되었습니다.",
    });
  } catch (err) {
    console.error("Contact API Error:", err);
    return NextResponse.json(
      { success: false, error: "서버 오류가 발생했습니다." },
      { status: 500 }
    );
  }
}
